version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    build: ./backend/
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend/
    volumes:
      - frontend_build:/app/build
    command: cp -r /app/build/. /frontend_build
    depends_on:
      - backend

  gateway:
    build: ./nginx/
    ports:
      - "8000:8000"
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static:/usr/share/nginx/html/static/
      - media:/media/
      - ./nginx/ssl:/etc/nginx/ssl/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
  frontend_build:
